import { useTranslation } from "react-i18next";

function Home() {
    const { t } = useTranslation(['common']);
    return (
        <div>
            <h1>{t('home')}</h1>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pulvinar, ligula eget blandit tempus, felis arcu scelerisque dolor, vel egestas orci arcu in erat. Cras viverra nulla id augue venenatis ultricies. Mauris ac nulla vel ipsum viverra pellentesque. Maecenas viverra sodales dolor, ac consequat mauris bibendum ac. Nunc efficitur dolor sit amet lacinia consectetur. Aenean lacinia enim in elit hendrerit, ac semper dolor porttitor. Etiam feugiat sem tempor, facilisis nulla a, mattis lectus. In laoreet suscipit arcu, vitae fermentum mi. Curabitur condimentum iaculis neque ut rutrum. Maecenas rhoncus elementum enim, at tincidunt purus ullamcorper dignissim. Aenean luctus, leo et euismod ultricies, nulla nulla fermentum ipsum, sed porta augue felis et metus. Pellentesque facilisis erat sed ipsum viverra volutpat. Aenean luctus felis nec nisl vulputate pulvinar at id turpis. Nulla facilisi.
                Phasellus dui libero, eleifend dictum dui ac, dignissim iaculis ipsum. Cras luctus elit neque, sit amet cursus nisl bibendum ut. Suspendisse accumsan efficitur diam quis facilisis. Aenean pulvinar venenatis enim, eget facilisis velit consequat vulputate. Integer est justo, ultricies vel maximus sit amet, vestibulum nec ex. Fusce facilisis, ligula eu maximus fringilla, risus nulla consectetur tortor, in euismod felis libero a urna. Nulla accumsan ut metus vitae malesuada. Integer vitae elit malesuada, suscipit ipsum eu, vehicula neque. Aliquam molestie enim et diam efficitur sollicitudin. Praesent tempus consectetur lorem sit amet iaculis. Integer nec nisi sed risus blandit tempor. Morbi pharetra a eros eu efficitur. Pellentesque sit amet nunc vitae tortor sodales sagittis. Ut sit amet nisi ac libero sagittis auctor.
                Cras placerat scelerisque lorem et consectetur. Aliquam a lorem iaculis, feugiat odio sit amet, posuere diam. Mauris vitae elit eget dolor facilisis hendrerit a eget purus. Aenean cursus sit amet urna nec tempor. Etiam in mollis justo. Donec semper tortor id tortor porta, non congue justo laoreet. Suspendisse aliquet nibh vitae orci rhoncus iaculis. Quisque ligula mi, commodo sit amet auctor vel, lacinia et urna. Cras tincidunt ipsum id quam auctor dignissim.
                Quisque id mattis ipsum, eget pellentesque odio. In volutpat ligula nec ex commodo, non mollis felis vulputate. Mauris ex urna, faucibus pulvinar tempus id, congue a arcu. Etiam quis aliquam est, non suscipit dui. Mauris a nisl efficitur, venenatis nisl nec, condimentum urna. Vestibulum pretium massa lobortis ullamcorper ullamcorper. Aliquam erat volutpat. Quisque ultrices magna nec diam rutrum, sit amet scelerisque orci congue.
                Aliquam ultrices facilisis mollis. Suspendisse urna velit, dignissim in dui in, elementum pharetra odio. Cras nec libero ut erat fringilla lacinia quis non elit. Maecenas convallis, mi id tincidunt sollicitudin, nisi nulla efficitur diam, vitae maximus nibh magna eget nulla. Curabitur vel pulvinar tortor. Ut pretium nisl ac erat condimentum, in sagittis leo luctus. Phasellus sit amet mauris at libero dapibus lobortis. Praesent facilisis, urna nec facilisis dapibus, ipsum nunc imperdiet arcu, in posuere tellus nisl sit amet ante. Curabitur et consequat ipsum. Phasellus neque tellus, blandit nec blandit eu, accumsan vel velit. Phasellus imperdiet tellus in odio commodo tempus. Nam vestibulum lacus elit, quis pellentesque orci imperdiet nec. 
            </p>
        </div>
    );
}

export default Home;